### PR TITLE
Added E, Exp, and Pi

### PR DESCRIPTION
**Pull request by guozhaonan**

### CODE REVIEW

**Comment by rwwagner90** [comment]
Hi @guozhaonan it looks like you have some failing tests because of a lint error from a console statement. Please use `Logger` instead. 

What is the use case for having these in the addon? I feel like `e` is kind of a concept that you should be calculating with in your JS and goes beyond the scope of the addon.

**Comment by guozhaonan** [comment]
Oh, that's strange... Will fix. 

As for the use case, I've sort of noticed this pattern in Ember of moving away from calculating in components and controllers and doing more calculations in the template. These functions aren't nearly as applicable as min, max or round but Pi and E definitely have uses in the template. 

On a completely different note, would having a helper function for Math.random() be useful?

**Comment by rwwagner90** [comment]
I don't think there is a trend of doing calculations in templates. It's generally frowned upon. I just think this PR is something that doesn't belong in this addon. `e` is not a basic arithmetic sort of thing.

**Comment by guozhaonan** [comment]
Hmm okay, would a random function be useful?

**Comment by rwwagner90** [comment]
I'm not sure how a random function would be useful myself, but it may have use to someone. The point of this addon was to do basic arithmetic, like all the stuff you learned before high school, basic stuff. I think all complex math and things like `e`, `cos`, `log`, etc. do not belong in this addon. However, I would be glad to help throw together an ember-complex-math-helpers (not sure about the name), and we could essentially implement every function available on `Math`. What do you think @guozhaonan?

**Comment by guozhaonan** [comment]
Oh, I guess that might make sense, although because you mentioned that it's frowned upon to do calculations in templates, perhaps it's not such a good idea?

**Comment by rwwagner90** [comment]
@guozhaonan yeah, it's definitely frowned upon, but if you had a use for it, I could help you with implementing it.

I'm going to close this as out of the scope of this addon.

**Pull request closed without merging**
